In [1]:
import numpy as np
import pandas as pd

In [2]:
arr1 = np.array([-1,-2,-3,-4,-5])

arr2 = np.abs(arr1)
arr2

array([1, 2, 3, 4, 5])

In [3]:
arr1 = np.array([1.534,3.5,22.5242,6.7,3.6])

arr2 = np.round(arr1)
arr2

array([ 2.,  4., 23.,  7.,  4.])

In [4]:
arr3 = np.arange(2,11).reshape(3,3)
arr3

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [5]:
list1 = [1,2,3,4,5,6,7,8]

list2 = pd.Series(list1)
list2

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [6]:
num_arr = np.array([1,2,3,3,4,5,6,7])

list4 = pd.Series(num_arr)
list4

0    1
1    2
2    3
3    3
4    4
5    5
6    6
7    7
dtype: int32

In [7]:
x = {
    "apple": "a sweet fruit",
    "book": "a set of written",
    "cat": "a small domesticated"
}
print(x)
y = pd.Series(x)
print(y)


{'apple': 'a sweet fruit', 'book': 'a set of written', 'cat': 'a small domesticated'}
apple           a sweet fruit
book         a set of written
cat      a small domesticated
dtype: object


In [8]:
num = np.arange(2,11)

df = pd.DataFrame(num.reshape(3,3))
df

0  1   2
0  2  3   4
1  5  6   7
2  8  9  10

In [9]:
array = np.arange(1, 13) 
df = pd.DataFrame(array.reshape(4, 3), columns=['Column1', 'Column2', 'Column3'])
print("DataFrame:\n", df)

DataFrame:
    Column1  Column2  Column3
0        1        2        3
1        4        5        6
2        7        8        9
3       10       11       12


In [10]:
num = np.array([1,2,3,4,5])

a = num[::-1]
a

array([5, 4, 3, 2, 1])

In [11]:
num1 = np.arange(2,11).reshape(3,3)
num1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [12]:
series = pd.Series([1, 1, 2, 3, 3, 3, 3, 3, 4, 4, 5])

fc = series.value_counts()
fc

3    5
1    2
4    2
2    1
5    1
Name: count, dtype: int64

In [13]:
data = {'A': [1, 2, None], 'B': [5, None, 7], 'C': [9, 10, 11]}
df = pd.DataFrame(data)

In [14]:
df

A    B   C
0  1.0  5.0   9
1  2.0  NaN  10
2  NaN  7.0  11

In [15]:
df.fillna(0)

A    B   C
0  1.0  5.0   9
1  2.0  0.0  10
2  0.0  7.0  11

In [18]:
dr = df['A'].fillna(df['A'].mean())
df = df.fillna(df.mean())

In [19]:
df

A    B   C
0  1.0  5.0   9
1  2.0  6.0  10
2  1.5  7.0  11

In [20]:
s = pd.Series([10, 20, 30, 40, 50, 60])
s[2]

30

In [29]:
s = pd.Series([10, 20, 30, 40, 50, 60])
positions = [1, 3, 4]
extracted_items = s.iloc[positions]
print(extracted_items)

1    20
3    40
4    50
dtype: int64


In [30]:
data = {'A': [1, 2, None], 'B': [5, None, None], 'C': [9, 10, 11]}
df = pd.DataFrame(data)

In [32]:
df.isnull().sum()

A    1
B    2
C    0
dtype: int64

In [33]:
import numpy as np
array = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
int_array = array.astype(int)
str_array = array.astype(str)

In [34]:
int_array

array([1, 2, 3, 4, 5])

In [35]:
str_array

array(['1.1', '2.2', '3.3', '4.4', '5.5'], dtype='<U32')

In [37]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2, 3], [4, 5, 6]])
c = np.array([[1, 2, 3], [4, 5, 6],[2,3,4]])
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
2
