In [1]:
import numpy as np
import pandas as pd

In [2]:
arr1 = np.array([-1,-2,-3,-4,-5])

arr2 = np.abs(arr1)
arr2

array([1, 2, 3, 4, 5])

In [3]:
arr1 = np.array([1.534,3.5,22.5242,6.7,3.6])

arr2 = np.round(arr1)
arr2

array([ 2.,  4., 23.,  7.,  4.])

In [4]:
arr3 = np.arange(2,11).reshape(3,3)
arr3

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [5]:
list1 = [1,2,3,4,5,6,7,8]

list2 = pd.Series(list1)
list2

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [6]:
num_arr = np.array([1,2,3,3,4,5,6,7])

list4 = pd.Series(num_arr)
list4

0    1
1    2
2    3
3    3
4    4
5    5
6    6
7    7
dtype: int32

In [9]:
x = {
    "apple": "a sweet fruit",
    "book": "a set of written",
    "cat": "a small domesticated"
}
print(x)
y = pd.Series(x)
print(y)


{'apple': 'a sweet fruit', 'book': 'a set of written', 'cat': 'a small domesticated'}
apple           a sweet fruit
book         a set of written
cat      a small domesticated
dtype: object
